### ISSUE TITLE
Add occlusion to the plug-in

### ISSUE THREAD

**Issue by Jake762x51** [kosumosu/x3daudio1_7_hrtf#11]
Often walls in buildings or in general cave section occlude the sound all together or muffle when it's very or rather thin but this is not the case with this plug-in in Skyrim/Skyrim VR.

Please add sound occlusion.

**Comment by kosumosu** [comment]
Unfortunately this is not possible with XAudio and X3DAudio. They have no idea of occlusion and do not work with any geometry. So I simply have not source of geometrical information about walls or anything.
In X3DAudio universe there's only sound source and listener.
So I'm sorry, but it can't be implemented.
