### ISSUE TITLE
Is subnautica supported / compatible?

### ISSUE THREAD

**Issue by vrokolos** [kosumosu/x3daudio1_7_hrtf#15]

**Comment by kosumosu** [comment]
No, Unity-based games are not supported.

**Comment by mrpenguinb** [comment]
Apparently Subnautica uses FMOD. Would X3DAudio HRTF work with it? I don't have high hopes.

**Comment by kosumosu** [comment]
You can use processxp to determine if Subnautica loads x3daudio2_7.dll. If it doesn't, then it won't work.

**Comment by mrpenguinb** [comment]
> You can use processxp to determine if Subnautica loads x3daudio2_7.dll. If it doesn't, then it won't work.

The game uses a local FMOD .dll, and it didn't load x3daudio in my testing with Process Explorer.
(the .dll is located at `Subnautica\Subnautica_Data\Plugins\fmodstudio.dll`).

I tried placing the x3daudio .dll in both the Plugins folder, and in with the .exe of the game itself, no changes.
You can close this issue, as the game definitely uses FMOD (in VR mode, it uses the Oculus spaitalizer I think).
