### ISSUE TITLE
[GAME SPECIFIC][Prey(2017)] game is based on unreal engine 4 but doesn't call x3daudio1_x.dll

### ISSUE THREAD

**Issue by jimmon89** [kosumosu/x3daudio1_7_hrtf#19]
so the problem i'm having, not sure if there is even a work-around, Prey 2017 never loads "x3daudio1_7.dll" or any other variant(not even from "%windir%\system32") but it does however load "xaudio2_7.dll"...
my question is, could there be some kind of techno-sorcery to either load x3daudio1_7 with an injector, or some kind of xaudio2_x to x3daudio1_x wrapper?
--edit--
ok so the injector method just made it crash
--edit 2--
nevermind, i found the issue, after some more digging it would seem that prey 2017 uses wwise api, not xaudio2 api

**Comment by kosumosu** [comment]
Hello! A game MUST load and use x3daudio1_7.dll in order for HRTF to work. "3d" is in it's name for purpose. It is this library though which we get 3D data about sound sources and listener. If game does not use it - we can't get this information, and without it we can't compute anything.

**Comment by jimmon89** [comment]
i found my issue and closed the ticket
