### ISSUE TITLE
Speech is in slow-mo(arma3)

### ISSUE THREAD

**Issue by Aapok** [kosumosu/x3daudio1_7_hrtf#2]
Hi! 

I was testing your new release with Arma 3 and found a bug.

The plugin now hooks to Arma and works, but there is a bug with npc speech that their voice gets really low and muffled like talking in slow-mo. Helicopter, gun and radio sounds are fine, but somehow the speech is broken.

I tested the game without the plugin and the speech was fine, so it seems the plugin causes this effect.

Cheers for working on this! I really like the project.

**Comment by kosumosu** [comment]
I confirm, I was able to reproduce it.

**Comment by kosumosu** [comment]
Probable cause: Doppler factor is not calculated or calculated incorrectly.

**Comment by kosumosu** [comment]
Yes, adding Doppler effect calculation fixed the issue.
https://github.com/kosumosu/x3daudio1_7_hrtf/releases/tag/v2.1
