### ISSUE TITLE
Doesn't work with Outer Worlds

### ISSUE THREAD

**Issue by phobos2077** [kosumosu/x3daudio1_7_hrtf#24]
Judging from Procmon output, mhr files are never loaded. Even if I make sure only the modified DLL is used by removing vanilla DLL from Windows\system32 folder and confirming via procmon.

Newer versions of UE4 is not supported?

**Comment by kosumosu** [comment]
Well, I did some debugging and I see that it creates mastering voice, couple of submix voices, but never any source voice.
So even though it loads XAudio2, it simply doesn't use it to output any sound.
UE4 team worked on rewriting their sound engine, so it seems, they have finally did it :)
Verdict: support for Outer Worlds is not possible.
