### ISSUE TITLE
XAUDIO2_DEFAULT_CHANNELS unhandled, causes issues with games that query count via GetVoiceDetails

### ISSUE THREAD

**Issue by emoose** [kosumosu/x3daudio1_7_hrtf#26]
First thanks for the great work on x3daudio1_7_hrtf, seems to be working pretty well with Resident Evil 4 👍 

There is one small issue though, the CRI middleware it uses for movies queries the number of channels in the mastering voice via `GetVoiceDetails`, and then uses the returned value as `DestinationChannels` param for `GetOutputMatrix`.

Sounds normal, except it seems the middleware first created the voice with `XAUDIO2_DEFAULT_CHANNELS` (0), on MSDN it's described as
> You can set InputChannels to XAUDIO2_DEFAULT_CHANNELS, which causes XAudio2 to try to detect the system speaker configuration setup.

This ends up with the game calling `GetOutputMatrix` with `DestinationChannels = 0`, which makes the DLL crash out.

Looking at the [code here for CreateMasteringVoice](https://github.com/kosumosu/x3daudio1_7_hrtf/blob/28cd541ee2cfee91f69b5099e202272d0710e4c8/x3daudio1_7/xaudio2-hook/graph/AudioGraphMapper.cpp#L141) it seems the number of channels shouldn't matter too much though, since it forces using 2 channels in there anyway - but before it's forced to 2, the parameter from the game gets stored into a `XAudio2MasteringVoiceProxy`, which is then where `GetVoiceDetails` retrieves the `InputChannels` value, causing the issue we see here.

I guess the reason original value is stored away might be to pretend to games that it's still using the channels they chose? If so I think `XAUDIO2_DEFAULT_CHANNELS` should probably be an exception there, seeing as it sounds like system changes the count based on speaker config anyway, so games shouldn't expect it to still be set as 0.

Not sure if you're still supporting x3daudio1_7_hrtf or not, but felt it was worth mentioning it here anyway, hope it can be fixed eventually!

For now I've just added a check at the start of `CreateMasteringVoice` to set InputChannels to 2 if it was 0, and now movies seem to be playing fine 😃

**Comment by kosumosu** [comment]
Hi, @emoose! Thanks for debugging!
Do you mean the Oculus version of RE4?
I you have a fix, you con just open pull request :)
I do not invest much time in this lib anymore since less and less games use x3daudio these days, but I can do small fixes like this one.

**Comment by emoose** [comment]
Nah this is for the RE4 UHD Steam release, afaik the Oculus one is android-only :( I'll make a PR for it shortly, not sure how correct this fix is though, but I'll mention that in the PR.

There was one other issue RE4 had with this, where the log file mentioned missing HRTF datasets for certain sample-rates, I know makehrtf/makemhr tool can be edited to create MHR with lower rates, but apparently that way might not be a great idea, I asked makemhr author about it here: https://github.com/kcat/openal-soft/issues/619

Seems OpenAL Soft would resample the audio to devices sample-rate first (usually 44100/48000), and then applies HRTF dataset for the devices sample-rate, but x3daudio1_7_hrtf doesn't seem to resample it before mixing HRTF, and just applies a HRTF dataset based on the audios sample-rate, which might be lower than device sample-rate.

From what kcat said on that issue it seems that might not be the best way to do it though, sounds like HRTF would work better at higher frequencies, and for that it'd need higher sample-rate to cover those frequencies, so if x3daudio could resample audio to device sample-rate first it should have a better effect.

Maybe I misunderstood something though, not sure, for now with RE4 I made a tool to resample the audio files themselves so that the higher samplerate datasets will be applied to them - but if you get a chance to work on x3daudio_hrtf again it'd be great if it could resample audio to device samplerate before applying HRTF, if it's possible at least.

**Comment by kosumosu** [comment]
Fixed the issue, RE4 now works well.
Here's new release: https://github.com/kosumosu/x3daudio1_7_hrtf/releases/tag/v2.4
Also added missing MHR files.
