### ISSUE TITLE
Resident Evil 4 Crashes

### ISSUE THREAD

**Issue by Ominousonion666** [kosumosu/x3daudio1_7_hrtf#28]
The game just crashes with this error message after loading a save or starting a new game.
![image](https://user-images.githubusercontent.com/45669443/151770522-749e6db2-ecf0-4307-a195-1fc750b98427.png)

(And yes, I already have Visual C++ Redistributable installed.)

**Comment by kosumosu** [comment]
What are the steps to reproduce this?
How frequently this happens?
Did you install xaudio_hrtf properly? (Should put `hrtf` folder directly into root game folder, one level above `Bin32`).

**Comment by Ominousonion666** [comment]
Yea my bad. I put the hrtf folder inside bin32.
