### ISSUE TITLE
Fallout 4 sound falls off too rapidly with 2.x

### ISSUE THREAD

**Issue by Supierce** [kosumosu/x3daudio1_7_hrtf#3]
With the 2.0 and 2.1 releases, most sounds now fall off too rapidly with distance (in Fallout 4). It's most noticeable with speech, where NPCs a few feet away are now much quieter. Radios at full volume are barely audible until you're right on top of them. Likewise with Magnolia's singing in the 3rd Rail. The original 1.0 release was fine.

If it helps, I play on a laptop with simple stereo headphones. Let me know if you need more information.

Love your work, BTW!

**Comment by kosumosu** [comment]
Thank you, Supierce!
I confirm the bug. I've just committed the fix, and new release will follow.

**Comment by kosumosu** [comment]
Release with the fix: https://github.com/kosumosu/x3daudio1_7_hrtf/releases/tag/v2.2
