### ISSUE TITLE
Muffled sounds

### ISSUE THREAD

**Issue by Drifter1234** [kosumosu/x3daudio1_7_hrtf#4]
Hello,

The sound is very muffled in Fallout 4. Is it being up or down sampled? I've used HRTF on System Shock 2 etc and the sound quality is not effected.

I cannot program, but it's an excellent tool and the game is much more immersive with it. However the sound quality is very poor.

The drop off in volume with distance is also quite steep - not sure if this is due to the HRTF table or some other variable.

Regards,

**Comment by kosumosu** [comment]
Hi!
What game are you talking about, first of all?

**Comment by Drifter1234** [comment]
Hi Roman,

It was Fallout 4 (I re-edited my post to make it a bit clearer).

I'm not sure what's causing it, but I saw a number of people on the nexus
mods site complain about it. An older version of your program was uploaded
there http://www.nexusmods.com/fallout4/mods/19680/?

It sounds similar to the filtering used in the Duke Nukem re-release

https://steamcommunity.com/app/434050/discussions/0/348292787746282373/

**Comment by kosumosu** [comment]
OK, what version of the mod did you use? The on from nexus (1.0)?
Could you provide a video of comparison vanilla vs mod?
I tested Fallout 4, and noticed no issues.

Regarding upsmpling: I don't know about Fallout 4, but Skyrim has most of the sounds at 8000-22050 Hz sample rate. So there is resampling, but it's the same for original game and the mod.

**Comment by Drifter1234** [comment]
You would not believe it, but I went to make a video then and it works flawlessly. I replicated this a number of times trying to fix it, so I'm not sure what happened.

So you don't think I'm a complete crankshaft, a couple of other people made the comments below. Exactly like I was hearing.

If it starts up again I'll see if I can isolate it. Sound fantastic btw, I have no idea why they went so far backwards on positional audio in the last decade.

_"The directional sound works superb, it's really, really cool! It changes the feeling of the game quiet a bit - for the better.
 
However, the overall sound degradation is very noticeable, unfortunately, and will keep me from using it - for now.
 
With this extension everything sounds like it has low bitrate, like a tin can, and there seem to be no lows, everything is a little too high pitched. And occasional crackles.
 
The extra immersion it gives, it takes away at the same time.
 
I really hope this can be improved, it would be sooo good! I see great potential here. Thanks for the work."

"Yeah I noticed the tinny effects applying to bullet impacts so I turned off the mod for now, seems like some kinks in the magic smoke box"_

**Comment by kosumosu** [comment]
Maybe you had some extra spatialization enabled, like 7.1 headphones...
Well, I'll close the issue for now.
Feel free to reopen if you find a way to reproduce it.

**Comment by Drifter1234** [comment]
No, nothing like that.

Perhaps a mod conflict of some sort

**Comment by Drifter1234** [comment]
It was just some weird issue with the sound card amp not initialising from sleep. So big woop..

If that was your skyrim comparison video on youtube, the vanilla comparison is about 1/4 of the volume if that. You should fix that or just pull that particular video.

Must be nice not being profoundly disabled by incompetent doctors and having the function to apply in practice the maths behind these sort of things... X = HX  etc etc..

**Comment by kosumosu** [comment]
I fixed that volume difference, The latest release should be fine on this regard.
And I'm too lazy to re-record and re-edit the video :)

**Comment by Drifter1234** [comment]
That was volume decay.

They don't know what hrtf is or what to listen for, so they fairly assume it's a crank when the comparison is so low.

Anyway, good luck with your life.
