### ISSUE TITLE
Cache FindFirstFileW file/enumeration results

### ISSUE THREAD

**Issue by Nukem9** [kosumosu/x3daudio1_7_hrtf#5]
I noticed this while debugging some things in Skyrim SE - it's just a suggestion. It seems like Bethesda calls `XAudio::CreateInstance` every time a sound is played and FindNextFileW gets called hundreds of times...

Log example: https://gist.github.com/Nukem9/05a0553620cb991db81e7bddf7e30df0
Line: https://github.com/kosumosu/x3daudio1_7_hrtf/blob/04aceb61eed8003f6c8e443aee80b7c53ae2d6cd/x3daudio1_7/application.cpp#L52

Thanks for this project by the way!

**Comment by kosumosu** [comment]
Creating IXAudio2 for each sound sounds... strange. But' I'll take a look...

**Comment by kosumosu** [comment]
Sorry for the delay. I added logging in the `create_xaudio_proxy` method. And after playing for some time, it only appeared once in the log. So I close the bug for now. If you find more detailed repro steps, feel free to reopen it.
